language: php

env:
  global:
    - SYMFONY__db_host=localhost
    - SYMFONY__db_port=3306
    - SYMFONY__db_user=root
    - SYMFONY__db_password=""

php:
  - 7.0

matrix:
  include:
    - php: 5.6
      env: SYMFONY_VERSION=2.8.*
    - php: 5.6
      env: SYMFONY_VERSION=3.0.*

before_install:
  - if [ "$SYMFONY_VERSION" != "" ]; then composer require "symfony/symfony:${SYMFONY_VERSION}" --no-update; fi;
  - echo "memory_limit=2G" >> ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/travis.ini

before_script:
  - composer update
  - mysql -e 'CREATE DATABASE sli_doctrineentitydatamapper'